/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import { useRef } from 'react';
import { Group } from 'three';
import gltf from "./assets/fishing-boat.gltf";
import { useMoveControls, useSurfaceBobbing } from './useBoatThings';

export default function FishingBoat(props: GroupProps) {
  const { nodes, materials } = useGLTF(gltf) as any;
  const group = useRef<Group>(null);
  const shipBodyGroup = useRef<Group>(null);
  useSurfaceBobbing(shipBodyGroup);
  useMoveControls(group);
  return (
    <group {...props} dispose={null} ref={group} castShadow>
      <group ref={shipBodyGroup}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={materials['mat_0-default-grey.jpg']}
      />
      <mesh
        geometry={nodes.mesh_1.geometry}
        material={materials['mat_1-boat_fishing02.jpg']}
      />
      </group>
    </group>
  )
}

useGLTF.preload(gltf)